### ISSUE TITLE
Attribute page

### ISSUE THREAD

**Issue by mark-henshaw** [diatum-org/dikota#3]
1. Change name of page to the attribute itself vs. "Attribute"
2. Label changes are not persisting.
![Attribute page](https://user-images.githubusercontent.com/79279818/119158881-8abd4b00-ba0b-11eb-8145-5f3120f87b3f.jpg)

**Comment by diatum-dev** [comment]
Thanks. I can reproduce the issue.

**Comment by diatum-dev** [comment]
Fixed in next release 0.6.99
